apiVersion: v1
kind: Service
metadata:
    name: homebox
    namespace: homebox
spec:
    selector:
        app: homebox
    ports:
        - port: 7745
          targetPort: 7745
          protocol: TCP
    type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: homebox
    namespace: homebox
spec:
    replicas: 1
    selector:
        matchLabels:
            app: homebox
    template:
        metadata:
            labels:
                app: homebox
        spec:
            containers:
                - name: homebox
                  image: ghcr.io/sysadminsmedia/homebox:main
                  ports:
                      - containerPort: 7745
                  env:
                      - name: HBOX_DATABASE_DRIVER
                        value: "postgres"
                      - name: HBOX_DATABASE_HOST
                        value: "postgres"
                      - name: HBOX_DATABASE_PORT
                        value: "5432"
                      - name: HBOX_DATABASE_DATABASE
                        value: "homebox"
                      - name: HBOX_DATABASE_NAME
                        valueFrom:
                            secretKeyRef:
                                name: postgres-creds
                                key: DATABASE_DATABASE
                      - name: HBOX_DATABASE_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: postgres-creds
                                key: POSTGRES_USER
                      - name: HBOX_DATABASE_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-creds
                                key: POSTGRES_PASSWORD
                      - name: HBOX_DATABASE_SSL_MODE
                        value: "disable"
                  volumeMounts:
                      - name: homebox-data
                        mountPath: /data
            volumes:
                - name: homebox-data
                  persistentVolumeClaim:
                      claimName: homebox-data-pvc
