apiVersion: v1
kind: Secret
metadata:
    name: postgres-creds
    namespace: homebox
type: Opaque
stringData:
    POSTGRES_PASSWORD: secret
    POSTGRES_USER: postgres
    DATABASE_DATABASE: homebox
