apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: homebox
    namespace: flux-system
spec:
    interval: 5m
    path: ./kubernetes-manifest/homebox
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
    validation: client
