name: Lint, Test, Build and Push Docker Image

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  job_check_all:
    name: Lint, Test Backend & Frontend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: homebox
          POSTGRES_PASSWORD: homebox
          POSTGRES_DB: homebox
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      ##########################################
      # Backend Phase
      ##########################################
      - name: Set working directory to backend
        run: echo "Backend phase starting"
        working-directory: backend

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Initialize Go module
        run: go mod tidy
        working-directory: backend

      - name: Lint Go code
        run: go vet ./...
        working-directory: backend

      - name: Run Go tests
        run: go test ./...
        working-directory: backend

      - name: Build Go project
        run: go build -o homebox
        working-directory: backend/app/api

      - name: Start backend server
        run: |
          ./homebox &
          echo $! > server.pid
        working-directory: backend/app/api

      - name: Wait for backend to be ready
        run: sleep 5

      ##########################################
      # Frontend Phase
      ##########################################

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U homebox -d homebox; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Lint and typecheck frontend
        run: |
          pnpm run lint:ci
          pnpm run typecheck
        working-directory: frontend

      - name: Run frontend integration tests
        run: pnpm test:ci
        working-directory: frontend

      - name: Stop backend server
        run: kill $(cat backend/app/api/server.pid)

  ##########################################
  # Docker Build & Push
  ##########################################
  job_docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: job_check_all
    if: ${{ success() }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: drashti114/homebox
        tags: |
          type=ref,event=branch
          type=sha

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
