name: CI/CD Pipeline

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Go mod tidy
        run: go mod tidy

      - name: Lint
        run: go vet ./...

      - name: Test
        run: go test ./...

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    needs: backend
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend
        run: go build -o homebox
        working-directory: backend/app/api

      - name: Start backend API
        run: |
          ./homebox &
        working-directory: backend/app/api

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Dependencies
        run: pnpm install

      - name: Lint frontend
        run: pnpm run lint:ci

      - name: Typecheck frontend
        run: pnpm run typecheck

      - name: Test frontend
        run: pnpm test:ci

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: ${{ success() }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag info
        id: vars
        run: |
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          
      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
           images: drashti114/homebox
           tags: |
              tags: |
                 type=raw,value=${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.short_sha }}-{{date "20060102-150405" tz="Asia/Kolkata"}}

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v6.0.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
