name: frontend
on:
  pull_request:
    branches:
      - drashtiladva-patch-1
  push:
    branches:
      - main
  workflow_call: {}
  
jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: frontend

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint frontend code
        run: pnpm run lint
 
  
